(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],page=window.HOBAH_PAGE||null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=t=>{let x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1800)};
const menu=$('#menuBtn'),drawer=$('#drawer'),back=$('#backdrop');
function openMenu(){drawer?.classList.add('open');back?.classList.add('open');drawer?.setAttribute('aria-hidden','false')}
function closeMenu(){drawer?.classList.remove('open');back?.classList.remove('open');drawer?.setAttribute('aria-hidden','true')}
menu&&menu.addEventListener('click',openMenu);$('#closeDrawer')?.addEventListener('click',closeMenu);back?.addEventListener('click',closeMenu);$$('#drawer a').forEach(a=>a.addEventListener('click',closeMenu));
const theme=localStorage.getItem('hobah:dark')==='1';document.body.classList.toggle('dark',theme);$('#themeBtn')?.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('hobah:dark',document.body.classList.contains('dark')?'1':'0')});
let saved=(()=>{try{return JSON.parse(localStorage.getItem('hobah:saved')||'[]')}catch{return[]}})();
function saveSaved(){localStorage.setItem('hobah:saved',JSON.stringify(saved));syncSaved()}
function syncSaved(){const b=$('#savedBtn');if(!b)return;const ref=page?`${page.slug}:${page.chapter}`:'';b.textContent=page&&saved.some(x=>x.ref===ref)?'♥':'♡'}syncSaved();
$('#savedBtn')?.addEventListener('click',()=>{if(page){const ref=`${page.slug}:${page.chapter}`,i=saved.findIndex(x=>x.ref===ref);if(i>=0){saved.splice(i,1);toast('Removed from saved')}else{saved.unshift({ref,slug:page.slug,title:page.title,chapter:page.chapter});toast('Chapter saved')}saveSaved();return}const d=$('#savedDialog');if(!d)return;$('#savedList').innerHTML=saved.length?saved.map(x=>`<a href="/read/${x.slug}/${x.chapter}/"><b>${esc(x.title)} ${x.chapter}</b><small>Open chapter</small></a>`).join(''):'<p>No saved chapters yet.</p>';d.showModal()});
$('#savedClose')?.addEventListener('click',()=>$('#savedDialog')?.close());
let studyDataPromise;
function loadStudyData(){if(window.MEB_STUDY_DATA)return Promise.resolve(window.MEB_STUDY_DATA);if(studyDataPromise)return studyDataPromise;studyDataPromise=new Promise((res,rej)=>{const s=document.createElement('script');s.src='/study-data-all.js?v=63';s.onload=()=>res(window.MEB_STUDY_DATA||{});s.onerror=rej;document.head.appendChild(s)});return studyDataPromise}
const dlg=$('#studyAiDialog'),msg=$('#studyAiMessages'),input=$('#studyAiInput');
function openStudy(seed=''){if(seed)input.value=seed;dlg?.showModal();setTimeout(()=>input?.focus(),40)}
$('#studyAiHeaderBtn')?.addEventListener('click',()=>openStudy());$('#studyAiClose')?.addEventListener('click',()=>dlg?.close());
async function context(){const d=page?await loadStudyData().catch(()=>({})):{};const b=page?d[page.slug]:null,sec=b?(b.sections||[]).find(s=>page.chapter>=s.start&&page.chapter<=s.end):null;return {currentReference:page?`${page.title} ${page.chapter}`:'Hobah Bible',scripture:page?page.verses.map(v=>`${v.v}. ${v.t}`).join(' ').slice(0,9000):'',bookBackground:b?[b.period,b.genre,b.overview,b.scholarship].filter(Boolean).join(' '):'',sectionContext:sec?`${sec.title}: ${sec.note}`:'',studyNotes:[]}}
function addMsg(role,text){const d=document.createElement('div');d.className='studyAiMsg '+role;d.innerHTML=`<small>${role==='user'?'YOU':'STUDY AI'}</small><p>${esc(text)}</p>`;msg.appendChild(d);msg.scrollTop=msg.scrollHeight;return d.querySelector('p')}
async function askStudy(q){addMsg('user',q);const out=addMsg('assistant','Thinking…');try{const r=await fetch('/api/study-chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:q,mode:'study',context:await context(),history:[]})});if(!r.ok)throw Error((await r.json().catch(()=>({}))).error||'Study AI unavailable');const rd=r.body.getReader(),dec=new TextDecoder();let buf='',ans='';while(true){const {done,value}=await rd.read();buf+=dec.decode(value||new Uint8Array(),{stream:!done});const ls=buf.split(/\n/);buf=ls.pop()||'';for(const l of ls){if(!l.startsWith('data:'))continue;const raw=l.slice(5).trim();if(!raw||raw==='[DONE]')continue;try{const j=JSON.parse(raw);if(typeof j.delta==='string')ans+=j.delta}catch{}}if(ans){out.textContent=ans;msg.scrollTop=msg.scrollHeight}if(done)break}if(!ans)out.textContent='No answer returned.';return ans}catch(e){out.textContent=e.message||'Study AI unavailable';return''}}
$('#studyAiForm')?.addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();if(!q)return;input.value='';askStudy(q)});
let corpora=null;
async function loadCorpora(){if(corpora)return corpora;const one=async n=>{const b64=await fetch('/'+n+'.b64').then(r=>r.text()),raw=atob(b64.trim()),u=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)u[i]=raw.charCodeAt(i);const ds=new DecompressionStream('gzip');return JSON.parse(await new Response(new Blob([u]).stream().pipeThrough(ds)).text())};corpora=await Promise.all(['ot','eth','nt'].map(one));return corpora}
$('#searchForm')?.addEventListener('submit',async e=>{e.preventDefault();const q=$('#searchInput')?.value.trim();if(!q)return;const sd=$('#searchDialog'),box=$('#searchResults');sd?.showModal();box.innerHTML='<p>Searching all 81 books…</p>';try{const cs=await loadCorpora(),terms=q.toLowerCase().split(/\s+/),hits=[];outer:for(const c of cs)for(const b of Object.values(c))for(const ch of b.chapters||[])for(const v of ch.verses||[]){const t=v.t.toLowerCase();if(terms.every(k=>t.includes(k))){hits.push({b:b.title,s:b.slug,c:ch.n,v:v.v,t:v.t});if(hits.length>=120)break outer}}box.innerHTML=hits.length?hits.map(x=>`<a class="searchResult" href="/read/${x.s}/${x.c}/#v${x.v}"><b>${esc(x.b)} ${x.c}:${x.v}</b><p>${esc(x.t)}</p></a>`).join(''):'<p>No matches found.</p>'}catch{box.innerHTML='<p>Search could not load. Please try again.</p>'}});$('#searchClose')?.addEventListener('click',()=>$('#searchDialog')?.close());
if(!page)return;
const audio=new Audio();let mode=localStorage.getItem('hobah:audioMode')||'normal',chunk=0,pausedAt=0,blobUrl='',busy=false;const chunks=[];for(let i=0;i<page.verses.length;i+=2)chunks.push(page.verses.slice(i,i+2));
function syncMode(){$$('[data-audio-mode]').forEach(b=>b.classList.toggle('active',b.dataset.audioMode===mode))}syncMode();$$('[data-audio-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.audioMode;localStorage.setItem('hobah:audioMode',mode);syncMode()}));
async function narrationText(i){let t=chunks[i].map(v=>`Verse ${v.v}. ${v.t}`).join(' ');if(i===0&&mode!=='normal'){const d=await loadStudyData().catch(()=>({})),b=d[page.slug],sec=b?(b.sections||[]).find(s=>page.chapter>=s.start&&page.chapter<=s.end):null;if(mode==='context'&&b)t=`Context. ${b.overview||''} ${sec?.note||''} Scripture. ${t}`;if(mode==='advanced'&&b)t=`Advanced context. ${b.period||''}. ${b.genre||''}. ${b.scholarship||''} ${sec?.note||''} Scripture. ${t}`}return t}
async function makeAudio(text,m=mode){const r=await fetch('/api/tts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text,voice:'marin',mode:m})});if(!r.ok)throw Error('Natural voice unavailable');return URL.createObjectURL(await r.blob())}
async function playChunk(i,from=0){if(busy||i>=chunks.length)return;if(i<0)i=0;chunk=i;busy=true;$('#audioStatus').textContent='Preparing natural voice…';try{if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=await makeAudio(await narrationText(i));audio.src=blobUrl;audio.onloadedmetadata=async()=>{try{audio.currentTime=Math.min(from||0,Math.max(0,audio.duration-.1))}catch{}await audio.play();busy=false;$('#audioStatus').textContent=`Reading ${page.title} ${page.chapter}`};audio.onended=()=>{chunk++;pausedAt=0;if(chunk<chunks.length)playChunk(chunk);else{const n=$('#nextChapter')?.href;$('#audioStatus').textContent='Chapter finished';if(n)setTimeout(()=>location.href=n,600)}}}catch{busy=false;$('#audioStatus').textContent='Natural voice unavailable'}}
$('#readPlay')?.addEventListener('click',()=>{if(audio.src&&!audio.ended){if(audio.paused){audio.play();$('#audioStatus').textContent='Reading'}else{audio.pause();pausedAt=audio.currentTime;$('#audioStatus').textContent='Paused'}}else playChunk(chunk,pausedAt)});$('#readRestart')?.addEventListener('click',()=>{audio.pause();chunk=0;pausedAt=0;playChunk(0)});
let voiceOn=false,rec=null,lastCmd='',lastCmdAt=0;function command(t){t=t.toLowerCase();const now=Date.now(),cmd=/explain( that| this)?/.test(t)?'explain':/stop|pause/.test(t)?'pause':/play|continue|resume/.test(t)?'play':'';if(!cmd||cmd===lastCmd&&now-lastCmdAt<1200)return;lastCmd=cmd;lastCmdAt=now;if(cmd==='pause'){audio.pause();pausedAt=audio.currentTime;$('#audioStatus').textContent='Paused by voice'}if(cmd==='play'){if(audio.src){audio.play()}else playChunk(chunk,pausedAt)}if(cmd==='explain')explainThat()}
function startRec(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){$('#voiceStatus').textContent='Not supported';return}rec=new R();rec.lang='en-AU';rec.continuous=true;rec.interimResults=true;rec.maxAlternatives=3;rec.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++)for(let j=0;j<e.results[i].length;j++)command(e.results[i][j].transcript)};rec.onend=()=>{if(voiceOn)setTimeout(()=>{try{rec.start()}catch{}},60)};rec.start();voiceOn=true;$('#voiceToggle').classList.add('active');$('#voiceStatus').textContent='Listening'}
$('#voiceToggle')?.addEventListener('click',()=>{if(voiceOn){voiceOn=false;try{rec?.stop()}catch{};$('#voiceToggle').classList.remove('active');$('#voiceStatus').textContent='Off'}else startRec()});
async function explainThat(){const resumeChunk=chunk,resumeTime=audio.currentTime||pausedAt||0;audio.pause();pausedAt=resumeTime;openStudy();const text=chunks[chunk]?.map(v=>`${v.v}. ${v.t}`).join(' ')||'';const ans=await askStudy(`Explain this passage in more detail: ${text}`);if(!ans)return;try{$('#audioStatus').textContent='Reading Study AI explanation…';const u=await makeAudio(ans,'advanced'),a=new Audio(u);await a.play();a.onended=()=>{URL.revokeObjectURL(u);chunk=resumeChunk;playChunk(resumeChunk,resumeTime)}}catch{$('#audioStatus').textContent='Explanation ready'}}
window.HOBAH_EXPLAIN=explainThat;
})();