const Study=(()=>{
  let annotations={method:{title:'Historical & Literary Study Notes',notice:'These notes are editorial study aids, not part of the biblical text. They distinguish traditional reception from modern historical-critical discussion where relevant and use cautious language when dating or authorship is disputed.',canonNotice:'This app follows the 81-item layout of this research edition. Ethiopian Orthodox canon counting can group and arrange books differently; the church’s published English list counts 46 Old Testament and 35 New Testament books.',sources:['Ethiopian Orthodox Tewahedo Church published canon list','Society of Biblical Literature / Bible Odyssey historical-literary resources','Standard historical-critical reference frameworks for ancient Israel, Second Temple Judaism, and the early Roman-period church']},books:{}}, books=[], ready=false, busy=false;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const readUser=()=>{try{const d=JSON.parse(localStorage.getItem('meb:user')||'{}');d.saved??=[];d.notes??={};d.savedStudy??=[];return d}catch{return {saved:[],notes:{},savedStudy:[]}}};
  const writeUser=d=>{localStorage.setItem('meb:user',JSON.stringify(d));const b=$('#savedBtn');if(b)b.textContent=((d.saved?.length||0)+(d.savedStudy?.length||0))?'♥':'♡'};
  const toast=t=>{let x=$('#studyToast');if(!x){x=document.createElement('div');x.id='studyToast';x.className='studyToast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1700)};
  const route=(slug,c,v='')=>`#read/${slug}/${c}${v?'/'+v:''}`;
  const sectionFor=(a,c)=>(a?.sections||[]).find(x=>c>=x.start&&c<=x.end)||null;
  const studyRef=(title,c,v=null)=>v?`${title} ${c}:${v} study`:`${title} ${c} study`;
  const saved=ref=>readUser().savedStudy.some(x=>x.ref===ref);
  const save=item=>{const d=readUser(),i=d.savedStudy.findIndex(x=>x.ref===item.ref);if(i>=0){d.savedStudy.splice(i,1);toast('Study note removed');writeUser(d);return false}d.savedStudy.unshift(item);writeUser(d);toast('Study note saved');return true};

  const terms=[
    [/\bYHWH\b/i,'YHWH','The four-letter divine name, often called the Tetragrammaton. This edition prints YHWH rather than replacing it with a title; its ancient vocalization is not preserved with certainty.'],
    [/\b(?:Christ|Messiah)\b/i,'Messiah / Christ','“Messiah” and Greek “Christ” both mean “anointed one.” The title can carry royal, priestly, or future-deliverer associations depending on context.'],
    [/\bcovenant\b/i,'Covenant','A binding relationship expressed through promise, obligation, sign, loyalty, and communal identity. Individual covenants should be read in their own literary setting.'],
    [/\b(?:law|Torah)\b/i,'Torah / law','Torah means instruction or teaching as well as law. The English word “law” can sound narrower than the biblical concept.'],
    [/\b(?:righteous|righteousness)\b/i,'Righteousness','Biblical righteousness can involve justice, right conduct, covenant faithfulness, or being “in the right”; context determines the emphasis.'],
    [/\bfaith\b/i,'Faith / faithfulness','Biblical faith-language can include trust, loyalty, conviction, and faithfulness. A single English word may cover several related nuances.'],
    [/\bkingdom\b/i,'Kingdom','Kingdom language often means active rule or reign as much as a territory. This is especially important in the Gospels’ “kingdom of God/heaven” language.'],
    [/\bspirit\b/i,'Spirit / breath / wind','Biblical words rendered “spirit” can carry associations of spirit, breath, or wind. Immediate context determines whether divine Spirit, human spirit, or another sense is intended.'],
    [/\btemple\b/i,'Temple','The Jerusalem temple was a worship center, priestly institution, economic center, and major symbol of divine presence and communal identity.'],
    [/\b(?:sacrifice|offering)\b/i,'Sacrifice / offering','Ancient offerings served distinct purposes including gift, thanksgiving, communion, purification, and reparation. “Sacrifice” is not one undifferentiated ritual category.'],
    [/\bSabbath\b/i,'Sabbath','Sabbath marks sacred time through cessation from ordinary labor. Biblical texts connect it with creation, covenant, liberation, worship, and social rest.'],
    [/\bPassover\b/i,'Passover','Passover commemorates Israel’s deliverance from Egypt and became a central festival whose practice and interpretation developed across Jewish history.'],
    [/\bZion\b/i,'Zion','“Zion” can name Jerusalem geographically, poetically, and theologically—especially as the site of divine presence, kingship, lament, and restoration hope.'],
    [/\bJerusalem\b/i,'Jerusalem','Jerusalem functions as historical city, royal capital, temple center, and theological symbol. Its destructions profoundly shaped biblical lament, exile, and restoration traditions.'],
    [/\bBabylon\b/i,'Babylon','Babylon can refer to the historical Mesopotamian city/empire; later apocalyptic texts can reuse the name symbolically for oppressive imperial power.'],
    [/\bEgypt\b/i,'Egypt','Egypt is both a real geopolitical power and a recurring scriptural symbol: place of refuge in some stories, bondage in Exodus, and a template for later “new exodus” imagery.'],
    [/\b(?:resurrection|raised from the dead|rise from the dead)\b/i,'Resurrection','Resurrection language concerns renewed embodied life after death, not simply the survival of a soul. Its articulation develops across later Jewish and early Christian literature.'],
    [/\bSon of Man\b/i,'Son of Man','The phrase can mean a human being, echo Daniel 7’s visionary figure, or function as a distinctive self-designation in the Gospels. Context matters.'],
    [/\bwisdom\b/i,'Wisdom','Biblical wisdom is practical, moral, theological, and observational. Wisdom books often preserve debate and multiple voices rather than one simple formula for life.'],
    [/\bgrace\b/i,'Grace','Grace emphasizes gift and favor. In the Greco-Roman world, benefaction and reciprocity provide important social background for this vocabulary.'],
    [/\bgospel\b/i,'Gospel','“Gospel” means good news. In early Christian usage it first names the proclaimed message about Jesus and God’s saving action, and later also written Gospel narratives.']
  ];

  function literary(a,text){const g=(a?.genre||'').toLowerCase(),t=text.trim(),n=[];
    if(/apocalypse|vision/.test(g))n.push('Apocalyptic and visionary writing communicates through symbols, scriptural echoes, heavenly scenes, and patterned imagery. Read the symbol in its ancient setting before mapping it onto later events.');
    else if(/wisdom/.test(g))n.push('Wisdom literature trains judgment through sayings, observation, dialogue, and paradox. A maxim may describe a dependable pattern without functioning as an unconditional promise.');
    else if(/poetry|prophe/.test(g))n.push('Poetic and prophetic language works through parallelism, metaphor, hyperbole, repeated images, and sound. The image may carry meaning that a flat literal paraphrase misses.');
    else if(/letter|epistle/.test(g))n.push('This verse belongs to an argument addressed to a particular community. Read paragraph flow and the issue being answered before isolating one sentence.');
    else if(/law|ritual/.test(g))n.push('Legal and ritual material belongs to an ancient covenant society. Modern labels such as “civil,” “ceremonial,” and “moral” are later analytical tools, not headings used by the text itself.');
    else if(/gospel/.test(g))n.push('Gospel narratives arrange remembered words and events to communicate theological meaning as well as story. Read the surrounding scene before harmonizing details with another Gospel.');
    else if(/narrative|history|novella|tale/.test(g))n.push('Narrative meaning develops through plot, characterization, repetition, speeches, and consequences. A character’s statement is not automatically the narrator’s endorsement.');
    if(/^(therefore|for |because|then |now )/i.test(t))n.push('The opening connective ties this verse to what comes immediately before it, so the prior argument or scene is part of its meaning.');
    if(/[“"]/u.test(t)&&/[”"]/u.test(t))n.push('Direct speech appears here. Note who is speaking, to whom, and whether the narrator affirms, challenges, or simply reports the statement.');
    if(/\bremember\b/i.test(t))n.push('“Remember” often means more than mental recall: it can call for covenant loyalty, public rehearsal, or action shaped by the remembered event.');
    return n.slice(0,2);
  }

  function bookPanel(a){if(!a)return '';return `<details class="studyBook"><summary><span><b>Book background</b><small>${esc(a.period)}</small></span><i>⌄</i></summary><div class="studyBody"><div class="studyFact"><small>GENRE</small><b>${esc(a.genre)}</b></div><p>${esc(a.overview)}</p><div class="studyCritical"><small>HISTORICAL-CRITICAL NOTE</small><p>${esc(a.scholarship)}</p></div><p class="studyDisclaimer">Editorial study aid — not part of the biblical text.</p></div></details>`}
  function sectionPanel(meta,a,sec,c){const ref=studyRef(meta.title,c),is=saved(ref);return `<details class="studySection"><summary><span class="studyStar">✦</span><span><b>Study context</b><small>Historical • literary • canonical</small></span><i>⌄</i></summary><div class="studyBody"><span class="studyTag">${esc(sec?.title||meta.title)}</span><p>${esc(sec?.note||a?.overview||'Read this chapter in the context of the whole book and its immediate literary unit.')}</p><div class="studyFacts"><div><small>PERIOD</small><b>${esc(a?.period||'')}</b></div><div><small>GENRE</small><b>${esc(a?.genre||'')}</b></div></div><button class="studySave sectionSave" data-ref="${esc(ref)}">${is?'♥ Saved study note':'♡ Save study note'}</button><p class="studyDisclaimer">Historical-literary commentary is editorial and separate from Scripture.</p></div></details>`}
  function versePanel(meta,a,sec,c,v,text){const ref=studyRef(meta.title,c,v),is=saved(ref),obs=literary(a,text),ks=terms.filter(x=>x[0].test(text)).slice(0,3);return `<div class="studyVerseInner"><div class="studyTop"><span>STUDY NOTE</span><b>${esc(meta.title)} ${c}:${v}</b></div><div class="studyBlock"><small>SECTION CONTEXT</small><h4>${esc(sec?.title||meta.title)}</h4><p>${esc(sec?.note||a?.overview||'Read this verse with the surrounding paragraph and chapter.')}</p></div>${obs.length?`<div class="studyBlock"><small>LITERARY OBSERVATION</small>${obs.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:''}${ks.length?`<div class="studyTerms">${ks.map(x=>`<div><small>KEY TERM</small><b>${esc(x[1])}</b><p>${esc(x[2])}</p></div>`).join('')}</div>`:''}<div class="studyBlock studyCompact"><small>BOOK HORIZON</small><p>${esc(a?.overview||'')}</p></div><button class="studySave verseStudySave" data-ref="${esc(ref)}" data-v="${v}">${is?'♥ Saved study note':'♡ Save study note'}</button><p class="studyDisclaimer">Editorial study note — not part of the biblical text.</p></div>`}

  async function enhance(){if(!ready||busy)return;const m=location.hash.match(/^#read\/([^/]+)\/(\d+)/);if(!m)return enhanceHomeOrLibrary();const [_,slug,cs]=m,c=+cs,meta=books.find(x=>x.slug===slug),a=annotations.books?.[slug];if(!meta||!a)return;const article=$('#chapterText');if(!article||article.dataset.studyEnhanced===`${slug}:${c}`)return;busy=true;try{
      const b=await fetch(`/data/${slug}.json`).then(r=>r.json()),chapter=b.chapters.find(x=>x.n===c)||b.chapters[0],sec=sectionFor(a,c);
      article.dataset.studyEnhanced=`${slug}:${c}`;
      const head=article.previousElementSibling;
      if(!document.querySelector('.studyBook'))(head||article).insertAdjacentHTML('beforebegin',bookPanel(a));
      if(!document.querySelector('.studySection'))article.insertAdjacentHTML('beforebegin',sectionPanel(meta,a,sec,c));
      const sectionSave=$('.sectionSave');if(sectionSave)sectionSave.onclick=()=>{const ref=sectionSave.dataset.ref,now=save({type:'section',ref,slug,chapter:c,title:sec?.title||`${meta.title} ${c} context`,text:sec?.note||a.overview});sectionSave.textContent=now?'♥ Saved study note':'♡ Save study note';enhanceHomeOrLibrary()};
      $$('.verse').forEach(p=>{if(p.dataset.studyAttached)return;p.dataset.studyAttached='1';const v=+p.dataset.v,verse=chapter.verses.find(x=>x.v===v);if(!verse)return;p.insertAdjacentHTML('afterend',`<button class="studyToggle" data-study-toggle="${v}"><span>✦ Study</span><span>⌄</span></button><div class="studyVerse hidden" id="study-${v}"></div>`)});
      $$('.studyToggle').forEach(btn=>btn.onclick=()=>{const v=+btn.dataset.studyToggle,box=$(`#study-${v}`),verse=chapter.verses.find(x=>x.v===v);if(!box||!verse)return;const open=box.classList.contains('hidden');if(open&&!box.dataset.ready){box.innerHTML=versePanel(meta,a,sec,c,v,verse.t);box.dataset.ready='1';const sv=box.querySelector('.verseStudySave');sv.onclick=()=>{const ref=sv.dataset.ref,obs=literary(a,verse.t),ks=terms.filter(x=>x[0].test(verse.t)).slice(0,3),text=[sec?.note||a.overview,...obs,...ks.map(x=>`${x[1]}: ${x[2]}`)].filter(Boolean).join(' '),now=save({type:'verse-study',ref,slug,chapter:c,verse:v,title:`Study note — ${meta.title} ${c}:${v}`,text});sv.textContent=now?'♥ Saved study note':'♡ Save study note';enhanceHomeOrLibrary()}}box.classList.toggle('hidden');btn.classList.toggle('open',open)});
    }catch(e){console.warn('Study layer:',e)}finally{busy=false}}

  function enhanceHomeOrLibrary(){const d=readUser(),home=$('#homeLibrary');if(home){const b=home.querySelector('b'),small=home.querySelector('small');if(b)b.textContent=`${(d.saved?.length||0)+d.savedStudy.length} saved`;if(small)small.textContent=`${Object.keys(d.notes||{}).length} personal • ${d.savedStudy.length} study note${d.savedStudy.length===1?'':'s'}`;if(!$('#studyMethodHome')&&annotations.method){const card=document.createElement('details');card.id='studyMethodHome';card.className='studyBook studyMethodHome';card.innerHTML=`<summary><span><b>${esc(annotations.method.title||'About the study notes')}</b><small>Method, sources & canon note</small></span><i>⌄</i></summary><div class="studyBody"><p>${esc(annotations.method.notice||'')}</p><div class="studyCritical"><small>CANON NOTE</small><p>${esc(annotations.method.canonNotice||'')}</p></div>${annotations.method.sources?.length?`<div class="studyBlock"><small>REFERENCE FRAMEWORK</small><ul>${annotations.method.sources.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}<p class="studyDisclaimer">Study material is editorial and visually separated from Scripture.</p></div>`;const anchor=$('.researchNote')||home;anchor.insertAdjacentElement('afterend',card)}}
    const lib=$('#libraryContent'),dlg=$('#libraryDialog');if(lib&&dlg?.open&&!$('#studyLibraryInjected')){if(d.savedStudy.length&&/no saved verses/i.test(lib.textContent||'')){const p=[...lib.querySelectorAll('p')].find(x=>/no saved verses/i.test(x.textContent||''));if(p)p.remove()}const wrap=document.createElement('div');wrap.id='studyLibraryInjected';wrap.className='studyLibraryInjected';wrap.innerHTML=d.savedStudy.length?`<h3>Saved Study Notes</h3>${d.savedStudy.map(x=>`<div class="libraryItem studySaved"><a href="${route(x.slug,x.chapter,x.verse||'')}">${esc(x.title||x.ref)}</a><p>${esc((x.text||'').slice(0,430))}</p><button class="studyRemove" data-ref="${esc(x.ref)}">Remove</button></div>`).join('')}`:'';lib.appendChild(wrap);$$('.studyRemove').forEach(btn=>btn.onclick=()=>{const u=readUser();u.savedStudy=u.savedStudy.filter(x=>x.ref!==btn.dataset.ref);writeUser(u);wrap.remove();enhanceHomeOrLibrary();toast('Study note removed')})}}

  async function init(){try{books=await fetch('/books.json').then(r=>r.json());annotations.books=window.MEB_STUDY_DATA||{};ready=true;const mo=new MutationObserver(()=>setTimeout(()=>{enhance();enhanceHomeOrLibrary()},20));mo.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['open']});window.addEventListener('hashchange',()=>setTimeout(enhance,40));setTimeout(enhance,100)}catch(e){console.warn('Study notes unavailable',e)}}
  return {init};
})();
Study.init();
