import { readFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const www=path.join(root,'www');
const must=['index.html','app.js','styles.css','native.css','native-bridge.js','native-audio.js','books.json','privacy.html','support.html'];
for(const f of must)if(!existsSync(path.join(www,f)))throw new Error('Missing native web asset: '+f);
const books=JSON.parse(await readFile(path.join(www,'books.json'),'utf8'));
if(books.length!==81)throw new Error(`Expected 81 books, found ${books.length}`);
const dataFiles=new Set(await readdir(path.join(www,'data')));
const missing=books.filter(b=>!dataFiles.has(`${b.slug}.json`));
if(missing.length)throw new Error('Missing offline books: '+missing.map(b=>b.slug).join(', '));
for(const cat of ['ot','eth','nt']){
  const p=path.join(www,'search',`${cat}.json`);
  if(!existsSync(p))throw new Error('Missing pre-expanded offline search corpus: '+cat);
  if(existsSync(path.join(www,`${cat}.b64`)))throw new Error('Duplicate compressed native search corpus still present: '+cat);
  const corpus=JSON.parse(await readFile(p,'utf8'));
  if(!corpus||typeof corpus!=='object'||!Object.keys(corpus).length)throw new Error('Empty offline search corpus: '+cat);
}
const app=await readFile(path.join(www,'app.js'),'utf8');
if(/fetch\(['"]\/api\//.test(app))throw new Error('Native app still contains same-origin API fetches');
for(const endpoint of ['/api/tts','/api/study-chat','/api/realtime-study'])if(!app.includes(`apiURL('${endpoint}')`))throw new Error('Remote native endpoint missing: '+endpoint);
if(app.includes('DecompressionStream'))throw new Error('Native app still decompresses search data at runtime');
if(!app.includes("fetch('/search/'+cat+'.json'"))throw new Error('Native app is not using local expanded search data');
if(!app.includes('HOBAH_NETWORK_CONNECTED===false'))throw new Error('Native offline API guards are missing');
for(const needle of ['HobahNativeAudio.play','hobah:native-audio-ended','hobah:native-audio-next','hobah:native-audio-previous'])if(!app.includes(needle))throw new Error('Native Scripture audio integration missing: '+needle);
for(const needle of ['HobahNativeVoice.start','hobah:native-voice-transcript','handleVoice(text','save that','explain that'])if(!app.includes(needle))throw new Error('Native Voice Study integration missing: '+needle);
const html=await readFile(path.join(www,'index.html'),'utf8');
for(const needle of ['native-bridge.js','native-audio.js','native.css','bottomAbout'])if(!html.includes(needle))throw new Error('Native HTML integration missing: '+needle);
if(!app.includes('HobahNativeReady')||!app.includes('HobahNativeAudioReady'))throw new Error('Native bootstrap does not wait for device/audio bridges');
const bridge=await readFile(path.join(www,'native-bridge.js'),'utf8');
if(!bridge.includes('HOBAH_NETWORK_CONNECTED'))throw new Error('Native connectivity bridge missing');
const audioBridge=await readFile(path.join(www,'native-audio.js'),'utf8');
for(const needle of ['HobahAudio','HobahVoice','HobahNativeVoice','native-voice-transcript'])if(!audioBridge.includes(needle))throw new Error('Native audio/voice bridge missing: '+needle);
const swiftRoot=path.join(root,'plugins','hobah-audio','ios','Sources','HobahNativeAudio');
const audioSwift=path.join(swiftRoot,'HobahAudioPlugin.swift');
const voiceSwift=path.join(swiftRoot,'HobahVoicePlugin.swift');
if(!existsSync(audioSwift))throw new Error('Native Swift audio plugin source missing');
if(!existsSync(voiceSwift))throw new Error('Native Swift Voice Study plugin source missing');
const voiceSource=await readFile(voiceSwift,'utf8');
for(const needle of ['SFSpeechRecognizer','AVAudioEngine','setVoiceProcessingEnabled','notifyListeners("transcript"'])if(!voiceSource.includes(needle))throw new Error('Native Swift Voice Study source incomplete: '+needle);
console.log(`Hobah iOS doctor passed • ${books.length} offline books • pre-expanded search • native AVFoundation audio • native Voice Study • native API bridge ready`);
