import { readFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const www=path.join(root,'www');
const must=['index.html','app.js','styles.css','native.css','native-bridge.js','books.json','privacy.html','support.html'];
for(const f of must)if(!existsSync(path.join(www,f)))throw new Error('Missing native web asset: '+f);
const books=JSON.parse(await readFile(path.join(www,'books.json'),'utf8'));
if(books.length!==81)throw new Error(`Expected 81 books, found ${books.length}`);
const dataFiles=new Set(await readdir(path.join(www,'data')));
const missing=books.filter(b=>!dataFiles.has(`${b.slug}.json`));
if(missing.length)throw new Error('Missing offline books: '+missing.map(b=>b.slug).join(', '));
const app=await readFile(path.join(www,'app.js'),'utf8');
if(/fetch\(['"]\/api\//.test(app))throw new Error('Native app still contains same-origin API fetches');
for(const endpoint of ['/api/tts','/api/study-chat','/api/realtime-study'])if(!app.includes(`apiURL('${endpoint}')`))throw new Error('Remote native endpoint missing: '+endpoint);
const html=await readFile(path.join(www,'index.html'),'utf8');
for(const needle of ['native-bridge.js','native.css','bottomAbout'])if(!html.includes(needle))throw new Error('Native HTML integration missing: '+needle);
if(!app.includes('HobahNativeReady'))throw new Error('Native preferences restore does not gate bootstrap');
console.log(`Hobah iOS doctor passed • ${books.length} offline books • native API bridge ready`);
